title: Christopher Wetzel # your name (or website title) here
logo: "/images/keegan wedding 4 siblings solo zoomed.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Driven Technical Engineer
  <br><br>
  Launching new products while finding innovative ways to automate processes
  <br><br>
  SQL | Tableau | Excel 
  <br><br>
  <a href="https://www.linkedin.com/in/cwetzel100/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
